### ISSUE TITLE
Static Tableviews don't hide section footers when hiding (the last?) rows

### ISSUE THREAD

**Issue by glenstorey** [peterpaulis/StaticDataTableViewController#18]
Hi there, 
Thanks for sharing this! 
When I hide the last row in a table it'll hide the section header, but not the section footer on a static UITableView. Is this an easy fix?

**Comment by drbarto** [comment]
@peterpaulis thanks for the great lib! Could you please integrate these two methods in the codebase? I use StaticDataTableViewController as a pod and therefore I'd rather not patch the code manually.

**Comment by anton-matosov** [comment]
Fixed in PR #28
