### ISSUE TITLE
Variable heightForRowAtIndexPath?

### ISSUE THREAD

**Issue by Antairez** [peterpaulis/StaticDataTableViewController#19]
For my static cells I have to determine each of their height according to its label height, but I also hide empty cells using [self cell:setHidden:]; The problem is that I have pre-scripted each static cell's section and row number, but when cells are hidden, the numbers become wrong. Is there a way to get around this? Can we not deduct the section and row numbers when we hide cells? Thank you.

**Comment by maplelover** [comment]
See https://github.com/maplelover/TVStaticTableViewController
