### ISSUE TITLE
reloadDataAnimated: changes contentOffset

### ISSUE THREAD

**Issue by nikitosorange** [peterpaulis/StaticDataTableViewController#21]
Every time i use hiding cells in my new project, it changes contentOffset of the tableView, so it looks buggy. Any ideas why this happens?

[self cell:self.sampleCell setHidden:![self cellIsHidden:sampleCell]];
[self reloadDataAnimated:NO];

**Comment by peterpaulis** [comment]
Did you try animated reload?

On Friday, July 10, 2015, nikitosorange <notifications@github.com> wrote:

> Every time i use hiding cells in my new project, it changes contentOffset
> of the tableView, so it looks buggy. Any ideas why this happens?
>
> [self cell:self.sampleCell setHidden:![self cellIsHidden:sampleCell]];
> [self reloadDataAnimated:NO];
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterpaulis/StaticDataTableViewController/issues/21>.
>


-- 
Prajem príjemný deň...
Mgr. Peter Paulis

**Comment by nikitosorange** [comment]
Yes, it makes the same issue appear.

**Comment by nikitosorange** [comment]
Hm, i suddenly found the way to avoid this bug. 
If I set these cells hidden on viewDidLoad and then show them just by [self cell:self.sampleCell setHidden:![self cellIsHidden:sampleCell]]; then everything is great.
And I don't even call reloadDataAnimated: here.
