### ISSUE TITLE
Can't call to setHeight method

### ISSUE THREAD

**Issue by WedgeSparda** [peterpaulis/StaticDataTableViewController#25]
I updated to the last version through Cocoapods but there ir no trace of the setHeight method you introduce in version 2.0.3.

**Comment by peterpaulis** [comment]
hi, it's

<pre>
- (void)cells:(NSArray *)cells setHeight:(CGFloat)height;
</pre>

**Comment by WedgeSparda** [comment]
Just uninstall, install again and tried again but got this

![captura de pantalla 2015-08-31 a las 11 48 34](https://cloud.githubusercontent.com/assets/48375/9576245/5ef1f214-4fd6-11e5-9ee6-6ccba9a31def.png)

Also, in StaticDataTableViewController.h there is those methods

````
- (BOOL)cellIsHidden:(UITableViewCell *)cell;

- (void)updateCell:(UITableViewCell *)cell;

- (void)updateCells:(NSArray *)cells;

- (void)cell:(UITableViewCell *)cell setHidden:(BOOL)hidden;

- (void)cells:(NSArray *)cells setHidden:(BOOL)hidden;

- (void)reloadDataAnimated:(BOOL)animated;
````

**Comment by peterpaulis** [comment]
Please try now to update to 2.0.5

**Comment by WedgeSparda** [comment]
Keeps telling me that 2.0.3 is the last version. It doesn't update.

**Comment by WedgeSparda** [comment]
Anything new about this?

**Comment by peterpaulis** [comment]
Hi, i did updated the pod to 2.0.5 not sure why 2.0.3 is downloaded, anyway, you can update it manually

**Comment by WedgeSparda** [comment]
Just checked the cocoapods site and got this

![captura de pantalla 2015-09-01 a las 10 37 32](https://cloud.githubusercontent.com/assets/48375/9599637/aca51184-5095-11e5-8688-1e57ef350e45.png)

Still showing the 2.0.3 version. Did you deploy the 2.0.5 version with 'pod trunk push [NAME.podspec]`?

**Comment by peterpaulis** [comment]
i see now what the problem is 

[!] You are not allowed to push new versions for this pod.

**Comment by peterpaulis** [comment]
whn i try to claim the pod i get Internal Server Error... nice

**Comment by WedgeSparda** [comment]
Just updated to 2.0.5 :dancer: 

Thanks
