### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by eytanschulman** [peterpaulis/StaticDataTableViewController#27]
Converting the main class to Swift for it's use directly in Swift. Or potentially the steps to using it with Swift.

**Comment by peterpaulis** [comment]
Hi, i'am not planning to support Swift anytime soon

thanks

**Comment by harshilshah** [comment]
Any update on this?

**Comment by muyexi** [comment]
I built a Swift version here: https://github.com/muyexi/StaticTableViewController.
